//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionACurso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATFDeportista
    {
        public int DeportistaId { get; set; }
        public bool CopiaDNI { get; set; }
        public Nullable<bool> CopiaDNIApoderado { get; set; }
        public bool AvalMedico { get; set; }
        public bool CompromisoRetorno { get; set; }
        public int Expedienteid { get; set; }
    
        public virtual ATFExpediente ATFExpediente { get; set; }
    }
}
