//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionACurso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASETIMES
    {
        public Nullable<double> YEAR { get; set; }
        public string COURSE { get; set; }
        public string GENDER { get; set; }
        public Nullable<double> RELAY__COUNT { get; set; }
        public Nullable<double> DISTANCE { get; set; }
        public string STROKE { get; set; }
        public string BASETIME { get; set; }
        public Nullable<double> SEGUNDOS { get; set; }
        public int tiempoId { get; set; }
    }
}
