//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionACurso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calendario()
        {
            this.ATFExpediente = new HashSet<ATFExpediente>();
        }
    
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fin { get; set; }
        public string Evento { get; set; }
        public string Sede { get; set; }
        public string Carácter { get; set; }
        public string Observación { get; set; }
        public string Organizador { get; set; }
        public int EventoId { get; set; }
        public int DisciplinaId { get; set; }
        public bool Internacional { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATFExpediente> ATFExpediente { get; set; }
        public virtual Disciplina Disciplina { get; set; }
    }
}
