//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionACurso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConFechas
    {
        public System.DateTime INICIO { get; set; }
        public System.DateTime FINAL { get; set; }
        public string EVENTOS { get; set; }
        public string CIUDAD { get; set; }
        public string PAIS { get; set; }
        public string MODALIDAD { get; set; }
        public string F7 { get; set; }
        public string Organiza { get; set; }
        public string Nota { get; set; }
        public int CalendarioId { get; set; }
    }
}
