//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionACurso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntrenadorInscrito
    {
        public int EntrenadorInscritoId { get; set; }
        public int EntrenadorId { get; set; }
        public int MeetId { get; set; }
    
        public virtual Entrenadores Entrenadores { get; set; }
        public virtual Torneo Torneo { get; set; }
    }
}
