//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionACurso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public Nullable<short> Event_no { get; set; }
        public string Event_ltr { get; set; }
        public int Event_ptr { get; set; }
        public string Ind_rel { get; set; }
        public string Event_sex { get; set; }
        public string Event_gender { get; set; }
        public Nullable<float> Event_dist { get; set; }
        public string Event_stroke { get; set; }
        public Nullable<short> Low_age { get; set; }
        public Nullable<short> High_Age { get; set; }
        public bool Multi_age { get; set; }
        public string Event_stat { get; set; }
        public Nullable<short> Event_rounds { get; set; }
        public Nullable<short> Num_prelanes { get; set; }
        public Nullable<short> Num_finlanes { get; set; }
        public string Heats_infinal { get; set; }
        public Nullable<short> Heats_insemi { get; set; }
        public string Std_lanes { get; set; }
        public bool Auto_seed { get; set; }
        public bool Twoperlane_req { get; set; }
        public string Preheat_order { get; set; }
        public string Finheat_order { get; set; }
        public bool Score_event { get; set; }
        public Nullable<short> Div_no { get; set; }
        public Nullable<short> Relay_size { get; set; }
        public string Comm_1 { get; set; }
        public string Comm_2 { get; set; }
        public string Comm_3 { get; set; }
        public string Comm_4 { get; set; }
        public Nullable<decimal> Entry_fee { get; set; }
        public bool Is_locked { get; set; }
        public string Locked_by { get; set; }
        public string Event_Type { get; set; }
        public string Locked_list { get; set; }
        public string Event_note { get; set; }
        public bool Suppress_stroke { get; set; }
        public bool Custom_ABCFinal { get; set; }
        public Nullable<short> Num_dives { get; set; }
        public Nullable<short> Num_HeatsInFinal { get; set; }
        public bool Multiage_SuperFinal { get; set; }
        public bool Finals_LanesVary { get; set; }
        public string Finals_LanesVaryOrder { get; set; }
        public string ABCfinal_order { get; set; }
        public bool ABC_Style { get; set; }
        public bool PrelimsAs_ExtendedFinal { get; set; }
        public Nullable<short> Num_LanesInBestHeatsTimedFinal { get; set; }
        public Nullable<short> Num_BestHeatsTimedFinal { get; set; }
        public bool TimedFinal_LanesVary { get; set; }
        public bool ScoreTimedFinal_asABC { get; set; }
        public Nullable<short> Num_HeatsInTimedFinalToScore { get; set; }
        public bool Pads_BothEnds { get; set; }
        public bool Multiage_SuperSeed { get; set; }
        public bool Suppress_distance { get; set; }
        public bool Fin_AwardsPrinted { get; set; }
        public bool Pre_AwardsPrinted { get; set; }
        public bool Sem_AwardsPrinted { get; set; }
        public string FastTimeStd_Abbr { get; set; }
        public string SlowTimeStd_Abbr { get; set; }
        public bool SuperFinal_ElimOldAgeGrp { get; set; }
        public bool SeedMultiAge_OldToYoung { get; set; }
        public bool Multi_ageScnd { get; set; }
        public Nullable<short> Num_RelayLegs { get; set; }
        public bool Pads_BothEndsFinals { get; set; }
        public Nullable<int> Checkin_starttime { get; set; }
        public Nullable<int> Checkin_endtime { get; set; }
        public Nullable<System.DateTime> Checkin_startdate { get; set; }
        public Nullable<System.DateTime> Checkin_enddate { get; set; }
        public Nullable<short> Num_semlanes { get; set; }
        public Nullable<short> EvtMaxAgeFor_CFinal { get; set; }
        public Nullable<short> EvtMaxAgeNumHeats_CFinal { get; set; }
        public Nullable<int> fin_actualstarttime { get; set; }
        public Nullable<int> sem_actualstarttime { get; set; }
        public Nullable<int> pre_actualstarttime { get; set; }
        public int EventId { get; set; }
        public int MeetId { get; set; }
    
        public virtual Torneo Torneo { get; set; }
    }
}
