//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionACurso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialTraspasos
    {
        public int HistorialId { get; set; }
        public int UsuarioId { get; set; }
        public int ClubId { get; set; }
        public string DNI { get; set; }
        public int VieneDe { get; set; }
        public System.DateTime FechaTraspaso { get; set; }
        public Nullable<int> InscripcionId { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Inscripciones Inscripciones { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
