//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InscripcionACurso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pruebas
    {
        public int PruebaId { get; set; }
        public int distancia { get; set; }
        public string estilo { get; set; }
        public Nullable<double> FactorF { get; set; }
        public Nullable<double> FactorM { get; set; }
    }
}
