//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rankings
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public int EmpresaId { get; set; }
        public string Empresa1 { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Telefono2 { get; set; }
        public string Ciudad { get; set; }
        public string Pais { get; set; }
        public string Ubicacion { get; set; }
        public string Web { get; set; }
        public string Notas { get; set; }
    }
}
