//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rankings
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoloPartidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PoloPartidos()
        {
            this.PoloResultados = new HashSet<PoloResultados>();
        }
    
        public int PartidoId { get; set; }
        public int FechaId { get; set; }
        public int GrupoId { get; set; }
        public double Hora { get; set; }
        public string Sexo { get; set; }
        public int RondaId { get; set; }
        public int Equipo1 { get; set; }
        public int Equipo2 { get; set; }
        public Nullable<int> TorneoId { get; set; }
    
        public virtual PoloFechas PoloFechas { get; set; }
        public virtual PoloGrupos PoloGrupos { get; set; }
        public virtual PoloRondas PoloRondas { get; set; }
        public virtual PoloTorneo PoloTorneo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PoloResultados> PoloResultados { get; set; }
    }
}
