//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rankings
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionItem
    {
        public Nullable<int> Sess_order { get; set; }
        public Nullable<int> Sess_ptr { get; set; }
        public Nullable<int> Event_ptr { get; set; }
        public string Sess_rnd { get; set; }
        public string Rept_type { get; set; }
        public Nullable<int> Delay_seconds { get; set; }
        public bool Alt_With { get; set; }
        public Nullable<short> Timed_finalheats { get; set; }
        public Nullable<int> EventTo_AlternateWith { get; set; }
        public string Delay_desc { get; set; }
        public Nullable<short> AltHeats_StartCount { get; set; }
        public int SessitemId { get; set; }
        public int Meetid { get; set; }
    
        public virtual Torneo Torneo { get; set; }
    }
}
