//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afiliado
    {
        public Afiliado()
        {
            this.Inscripciones = new HashSet<Inscripciones>();
        }
    
        public int DeportistaId { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public string DNI { get; set; }
        public string Tipo_de_documento { get; set; }
        public System.DateTime Fecha_de_nacimiento { get; set; }
        public string Sexo { get; set; }
    
        public virtual ICollection<Inscripciones> Inscripciones { get; set; }
    }
}
