//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class atletas
    {
        public int Ath_no { get; set; }
        public string Last_name { get; set; }
        public string First_name { get; set; }
        public string Initial { get; set; }
        public string Ath_Sex { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public Nullable<int> Team_no { get; set; }
        public string Schl_yr { get; set; }
        public Nullable<short> Ath_age { get; set; }
        public string Reg_no { get; set; }
        public string Ath_stat { get; set; }
        public Nullable<int> Div_no { get; set; }
        public Nullable<int> Comp_no { get; set; }
        public string Pref_name { get; set; }
        public string Home_addr1 { get; set; }
        public string Home_addr2 { get; set; }
        public string Home_city { get; set; }
        public string Home_prov { get; set; }
        public string Home_statenew { get; set; }
        public string Home_zip { get; set; }
        public string Home_cntry { get; set; }
        public string Home_daytele { get; set; }
        public string Home_evetele { get; set; }
        public string Home_faxtele { get; set; }
        public string Home_email { get; set; }
        public string Citizen_of { get; set; }
        public string Picture_bmp { get; set; }
        public string second_club { get; set; }
        public string Home_celltele { get; set; }
        public string bcssa_type { get; set; }
        public string Home_emergcontact { get; set; }
        public string Home_emergtele { get; set; }
        public Nullable<short> Disab_Scode { get; set; }
        public Nullable<short> Disab_SBcode { get; set; }
        public Nullable<short> Disab_SMcode { get; set; }
        public string Disab_SDMSID { get; set; }
        public string Disab_Exeptioncodes { get; set; }
        public bool Masters_RegVerified { get; set; }
        public int AtletaId { get; set; }
        public int Meetid { get; set; }
        public int TeamId { get; set; }
    
        public virtual Equipos Equipos { get; set; }
        public virtual Torneo Torneo { get; set; }
    }
}
