//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarioCursos
    {
        public int EventoId { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fin { get; set; }
        public string Sede { get; set; }
        public int Disciplina { get; set; }
        public string Evento { get; set; }
        public string Organizador { get; set; }
        public string DirigidoA { get; set; }
        public string Requisito { get; set; }
        public string Horarios { get; set; }
        public string Enlace { get; set; }
    }
}
