//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendario
    {
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fin { get; set; }
        public string Evento { get; set; }
        public string Sede { get; set; }
        public string Carácter { get; set; }
        public string Observación { get; set; }
        public string Organizador { get; set; }
        public int EventoId { get; set; }
        public int DisciplinaId { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
    }
}
