//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambiosDNI
    {
        public int CambioId { get; set; }
        public string DNI { get; set; }
        public System.DateTime fecha { get; set; }
        public string DNIAntiguo { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
    }
}
