//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaNoticia
    {
        public CategoriaNoticia()
        {
            this.Noticias = new HashSet<Noticias>();
        }
    
        public int CategoriaId { get; set; }
        public string TipoNoticia { get; set; }
        public string Detalle { get; set; }
    
        public virtual ICollection<Noticias> Noticias { get; set; }
    }
}
