//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChopiTorneo
    {
        public ChopiTorneo()
        {
            this.ChopiClubesParticipantes = new HashSet<ChopiClubesParticipantes>();
            this.ChopiEventos = new HashSet<ChopiEventos>();
            this.ChopiOrganizador = new HashSet<ChopiOrganizador>();
            this.ChopiPuntajes = new HashSet<ChopiPuntajes>();
        }
    
        public int TorneoId { get; set; }
        public string Nombre { get; set; }
        public string Organizador { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
    
        public virtual ICollection<ChopiClubesParticipantes> ChopiClubesParticipantes { get; set; }
        public virtual ICollection<ChopiEventos> ChopiEventos { get; set; }
        public virtual ICollection<ChopiOrganizador> ChopiOrganizador { get; set; }
        public virtual ICollection<ChopiPuntajes> ChopiPuntajes { get; set; }
    }
}
