//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChopiPuntajes
    {
        public int PuntajeId { get; set; }
        public int TorneoId { get; set; }
        public int Puesto { get; set; }
        public int Puntos { get; set; }
        public bool IR { get; set; }
    
        public virtual ChopiTorneo ChopiTorneo { get; set; }
    }
}
