//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChopiClubes
    {
        public ChopiClubes()
        {
            this.ChopiClubesParticipantes = new HashSet<ChopiClubesParticipantes>();
            this.ChopiDeportistas = new HashSet<ChopiDeportistas>();
            this.ChopiOrganizador = new HashSet<ChopiOrganizador>();
        }
    
        public int ClubId { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
        public string Siglas { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public bool Activo { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<ChopiClubesParticipantes> ChopiClubesParticipantes { get; set; }
        public virtual ICollection<ChopiDeportistas> ChopiDeportistas { get; set; }
        public virtual ICollection<ChopiOrganizador> ChopiOrganizador { get; set; }
    }
}
