//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChopiDeportistas
    {
        public ChopiDeportistas()
        {
            this.ChopiInscripciones = new HashSet<ChopiInscripciones>();
            this.ChopiPostas = new HashSet<ChopiPostas>();
        }
    
        public int DeportistaId { get; set; }
        public int ClubId { get; set; }
        public string Nombres { get; set; }
        public string Apellido { get; set; }
        public string Materno { get; set; }
        public System.DateTime Nacimiento { get; set; }
        public string DNI { get; set; }
        public int SexoId { get; set; }
    
        public virtual ChopiClubes ChopiClubes { get; set; }
        public virtual ChopiSexos ChopiSexos { get; set; }
        public virtual ICollection<ChopiInscripciones> ChopiInscripciones { get; set; }
        public virtual ICollection<ChopiPostas> ChopiPostas { get; set; }
    }
}
