//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Appaterno { get; set; }
        public string Apmaterno { get; set; }
        public string Telefono { get; set; }
        public string Extension { get; set; }
        public Nullable<int> Planta { get; set; }
        public Nullable<int> Asiento { get; set; }
        public string Cargo { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public string Celular { get; set; }
        public string Observaciones { get; set; }
        public string Email { get; set; }
    }
}
