//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoInscripcion
    {
        public int InscripcionId { get; set; }
        public int ParticipanteId { get; set; }
        public int CursoId { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual CursoParticipante CursoParticipante { get; set; }
    }
}
