//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoInscripcionPrograma
    {
        public CursoInscripcionPrograma()
        {
            this.CursoPago = new HashSet<CursoPago>();
        }
    
        public int InscripcionId { get; set; }
        public int AlumnoId { get; set; }
        public int CursoId { get; set; }
        public System.DateTime Pagado { get; set; }
    
        public virtual CursoAlumno CursoAlumno { get; set; }
        public virtual CursoCalentario CursoCalentario { get; set; }
        public virtual ICollection<CursoPago> CursoPago { get; set; }
    }
}
