//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoAlumno
    {
        public CursoAlumno()
        {
            this.CursoInscripcionPrograma = new HashSet<CursoInscripcionPrograma>();
            this.CursoProfesor = new HashSet<CursoProfesor>();
        }
    
        public int AlumnoId { get; set; }
        public string Nombres { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public string DNI { get; set; }
        public string Sexo { get; set; }
        public System.DateTime Nacimiento { get; set; }
        public string Direccion { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public Nullable<int> FotoId { get; set; }
    
        public virtual CursoFotos CursoFotos { get; set; }
        public virtual ICollection<CursoInscripcionPrograma> CursoInscripcionPrograma { get; set; }
        public virtual ICollection<CursoProfesor> CursoProfesor { get; set; }
    }
}
