//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoParticipante
    {
        public CursoParticipante()
        {
            this.CursoInscripcion = new HashSet<CursoInscripcion>();
        }
    
        public int ParticipanteId { get; set; }
        public string Nombres { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public System.DateTime Nacimiento { get; set; }
        public string DNI { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
        public string Nacionalidad { get; set; }
        public string Actividad { get; set; }
    
        public virtual ICollection<CursoInscripcion> CursoInscripcion { get; set; }
    }
}
