//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoCalentario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CursoCalentario()
        {
            this.CursoBanner = new HashSet<CursoBanner>();
            this.CursoHorario = new HashSet<CursoHorario>();
            this.CursoObjetivos = new HashSet<CursoObjetivos>();
            this.CursoProfesor = new HashSet<CursoProfesor>();
        }
    
        public int CursoId { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fin { get; set; }
        public string Sede { get; set; }
        public int DisciplinaId { get; set; }
        public string Evento { get; set; }
        public string Organizador { get; set; }
        public string DirigidoA { get; set; }
        public Nullable<int> CursoRequisito { get; set; }
        public string Enlace { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoBanner> CursoBanner { get; set; }
        public virtual Disciplina Disciplina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoHorario> CursoHorario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoObjetivos> CursoObjetivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CursoProfesor> CursoProfesor { get; set; }
    }
}
