//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directivos
    {
        public int DirectivoId { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public int ClubId { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
        public string Cargo { get; set; }
        public System.DateTime FinVigencia { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
