//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuentros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Encuentros()
        {
            this.Resultados = new HashSet<Resultados>();
        }
    
        public int EncuentroId { get; set; }
        public int Pais1 { get; set; }
        public int Pais2 { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Genero { get; set; }
        public string Ronda { get; set; }
        public string Grupo { get; set; }
    
        public virtual Pais Pais { get; set; }
        public virtual Pais Pais3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resultados> Resultados { get; set; }
    }
}
