//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrenadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entrenadores()
        {
            this.HistorialEntrenador = new HashSet<HistorialEntrenador>();
        }
    
        public int EntrenadorId { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string DNI { get; set; }
        public int Clubid { get; set; }
        public int EstadoId { get; set; }
        public System.DateTime Fecha_de_nacimiento { get; set; }
        public string Sexo { get; set; }
        public int AntiguoId { get; set; }
        public string RutaFoto { get; set; }
        public string Email1 { get; set; }
        public string Celular1 { get; set; }
        public string Celular2 { get; set; }
        public string Email2 { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual Antiguo Antiguo { get; set; }
        public virtual Club Club { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialEntrenador> HistorialEntrenador { get; set; }
    }
}
