//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoja1_
    {
        public int Número { get; set; }
        public string Grupo { get; set; }
        public string Género { get; set; }
        public string Equipo_1 { get; set; }
        public string Equipo_2 { get; set; }
        public string Q_1 { get; set; }
        public string Q_2 { get; set; }
        public string Q_3 { get; set; }
        public string Q_4 { get; set; }
        public string Resultado { get; set; }
        public int ResultadoId { get; set; }
    }
}
