//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcasMinimas
    {
        public Nullable<int> tag_ptr { get; set; }
        public string tag_gender { get; set; }
        public string tag_indrel { get; set; }
        public Nullable<int> tag_dist { get; set; }
        public string tag_stroke { get; set; }
        public Nullable<short> low_age { get; set; }
        public Nullable<short> high_Age { get; set; }
        public Nullable<float> tag_time { get; set; }
        public string tag_course { get; set; }
        public string div_abbr { get; set; }
        public int TimeStdId { get; set; }
        public int MeetId { get; set; }
    
        public virtual Torneo Torneo { get; set; }
    }
}
