//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetMasters
    {
        public MeetMasters()
        {
            this.RESULTSMasters = new HashSet<RESULTSMasters>();
        }
    
        public int Meet { get; set; }
        public string MName { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string Course { get; set; }
        public int MeetId { get; set; }
    
        public virtual ICollection<RESULTSMasters> RESULTSMasters { get; set; }
    }
}
