//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modals
    {
        public int Modalid { get; set; }
        public string Titulo { get; set; }
        public string Cuerpo { get; set; }
        public string Image { get; set; }
        public string Enlace { get; set; }
        public bool Activo { get; set; }
    }
}
