//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9B1F4C_FDPNEntities : DbContext
    {
        public DB_9B1F4C_FDPNEntities()
            : base("name=DB_9B1F4C_FDPNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Afiliacion> Afiliacion { get; set; }
        public DbSet<Afiliado> Afiliado { get; set; }
        public DbSet<Alertas> Alertas { get; set; }
        public DbSet<Antiguo> Antiguo { get; set; }
        public DbSet<Apagado> Apagado { get; set; }
        public DbSet<Asociaciones> Asociaciones { get; set; }
        public DbSet<ATFDeportista> ATFDeportista { get; set; }
        public DbSet<ATFExpediente> ATFExpediente { get; set; }
        public DbSet<Athlete> Athlete { get; set; }
        public DbSet<AthleteMasters> AthleteMasters { get; set; }
        public DbSet<atletas> atletas { get; set; }
        public DbSet<Banners> Banners { get; set; }
        public DbSet<BASETIMES> BASETIMES { get; set; }
        public DbSet<Calendario> Calendario { get; set; }
        public DbSet<CambiosDNI> CambiosDNI { get; set; }
        public DbSet<CategoriaNoticia> CategoriaNoticia { get; set; }
        public DbSet<Categorias> Categorias { get; set; }
        public DbSet<CategoriasMasters> CategoriasMasters { get; set; }
        public DbSet<ChopiCategorias> ChopiCategorias { get; set; }
        public DbSet<ChopiClubes> ChopiClubes { get; set; }
        public DbSet<ChopiClubesParticipantes> ChopiClubesParticipantes { get; set; }
        public DbSet<ChopiDeportistas> ChopiDeportistas { get; set; }
        public DbSet<ChopiEstados> ChopiEstados { get; set; }
        public DbSet<ChopiEstilos> ChopiEstilos { get; set; }
        public DbSet<ChopiEventos> ChopiEventos { get; set; }
        public DbSet<ChopiInscripciones> ChopiInscripciones { get; set; }
        public DbSet<ChopiOrganizador> ChopiOrganizador { get; set; }
        public DbSet<ChopiPostas> ChopiPostas { get; set; }
        public DbSet<ChopiPuntajes> ChopiPuntajes { get; set; }
        public DbSet<ChopiRoles> ChopiRoles { get; set; }
        public DbSet<ChopiSexos> ChopiSexos { get; set; }
        public DbSet<ChopiTorneo> ChopiTorneo { get; set; }
        public DbSet<Club> Club { get; set; }
        public DbSet<Comentario> Comentario { get; set; }
        public DbSet<Comentarios> Comentarios { get; set; }
        public DbSet<ConFechas> ConFechas { get; set; }
        public DbSet<Configuracion> Configuracion { get; set; }
        public DbSet<Contactos> Contactos { get; set; }
        public DbSet<Curso> Curso { get; set; }
        public DbSet<CursoAlumno> CursoAlumno { get; set; }
        public DbSet<CursoBanner> CursoBanner { get; set; }
        public DbSet<CursoCalentario> CursoCalentario { get; set; }
        public DbSet<CursoFotos> CursoFotos { get; set; }
        public DbSet<CursoHorario> CursoHorario { get; set; }
        public DbSet<CursoInscripcion> CursoInscripcion { get; set; }
        public DbSet<CursoInscripcionPrograma> CursoInscripcionPrograma { get; set; }
        public DbSet<CursoObjetivos> CursoObjetivos { get; set; }
        public DbSet<CursoPago> CursoPago { get; set; }
        public DbSet<CursoParticipante> CursoParticipante { get; set; }
        public DbSet<CursoProfesor> CursoProfesor { get; set; }
        public DbSet<Delegados> Delegados { get; set; }
        public DbSet<Directivos> Directivos { get; set; }
        public DbSet<Disciplina> Disciplina { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<Entradas> Entradas { get; set; }
        public DbSet<Entrenadores> Entrenadores { get; set; }
        public DbSet<EntrenadorInscrito> EntrenadorInscrito { get; set; }
        public DbSet<Equipos> Equipos { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Estilos> Estilos { get; set; }
        public DbSet<Eventos> Eventos { get; set; }
        public DbSet<Fotos> Fotos { get; set; }
        public DbSet<HistorialdeAfiliaciones> HistorialdeAfiliaciones { get; set; }
        public DbSet<HistorialEntrenador> HistorialEntrenador { get; set; }
        public DbSet<HistorialTraspasos> HistorialTraspasos { get; set; }
        public DbSet<Inscripciones> Inscripciones { get; set; }
        public DbSet<InscripcionResponsable> InscripcionResponsable { get; set; }
        public DbSet<Landing> Landing { get; set; }
        public DbSet<MarcasMinimas> MarcasMinimas { get; set; }
        public DbSet<Meet> Meet { get; set; }
        public DbSet<MeetMasters> MeetMasters { get; set; }
        public DbSet<Modals> Modals { get; set; }
        public DbSet<Multas> Multas { get; set; }
        public DbSet<MultiEdad> MultiEdad { get; set; }
        public DbSet<Noticias> Noticias { get; set; }
        public DbSet<OtroAtleta> OtroAtleta { get; set; }
        public DbSet<OtroCategorias> OtroCategorias { get; set; }
        public DbSet<OtroEntradas> OtroEntradas { get; set; }
        public DbSet<OtroEquipo> OtroEquipo { get; set; }
        public DbSet<OtroEventos> OtroEventos { get; set; }
        public DbSet<OtroGrupal> OtroGrupal { get; set; }
        public DbSet<OtroResponsable> OtroResponsable { get; set; }
        public DbSet<OtroSetupTorneo> OtroSetupTorneo { get; set; }
        public DbSet<OtroTorneo> OtroTorneo { get; set; }
        public DbSet<PAlumno> PAlumno { get; set; }
        public DbSet<PCalendario> PCalendario { get; set; }
        public DbSet<PCurso> PCurso { get; set; }
        public DbSet<PHorarios> PHorarios { get; set; }
        public DbSet<Piscinas> Piscinas { get; set; }
        public DbSet<PObjetivos> PObjetivos { get; set; }
        public DbSet<PoloEquipos> PoloEquipos { get; set; }
        public DbSet<PoloFechas> PoloFechas { get; set; }
        public DbSet<PoloGoleadores> PoloGoleadores { get; set; }
        public DbSet<PoloGrupos> PoloGrupos { get; set; }
        public DbSet<PoloJugadores> PoloJugadores { get; set; }
        public DbSet<PoloPartidos> PoloPartidos { get; set; }
        public DbSet<PoloPosicion> PoloPosicion { get; set; }
        public DbSet<PoloPosicionFinal> PoloPosicionFinal { get; set; }
        public DbSet<PoloResultados> PoloResultados { get; set; }
        public DbSet<PoloRondas> PoloRondas { get; set; }
        public DbSet<PoloSetupTorneo> PoloSetupTorneo { get; set; }
        public DbSet<PoloTorneo> PoloTorneo { get; set; }
        public DbSet<PPersona> PPersona { get; set; }
        public DbSet<PProfesor> PProfesor { get; set; }
        public DbSet<Procesado> Procesado { get; set; }
        public DbSet<Pruebas> Pruebas { get; set; }
        public DbSet<PTemas> PTemas { get; set; }
        public DbSet<Records> Records { get; set; }
        public DbSet<RecordsActuales> RecordsActuales { get; set; }
        public DbSet<RecordsEdades> RecordsEdades { get; set; }
        public DbSet<RecordsPruebas> RecordsPruebas { get; set; }
        public DbSet<RecordTipo> RecordTipo { get; set; }
        public DbSet<RESULTS> RESULTS { get; set; }
        public DbSet<RESULTSMasters> RESULTSMasters { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Saltos> Saltos { get; set; }
        public DbSet<Sesion> Sesion { get; set; }
        public DbSet<SessionItem> SessionItem { get; set; }
        public DbSet<SetupTorneo> SetupTorneo { get; set; }
        public DbSet<Suscritos> Suscritos { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TagNames> TagNames { get; set; }
        public DbSet<TatoInformeAsistencias> TatoInformeAsistencias { get; set; }
        public DbSet<TatoInformeEntrenador> TatoInformeEntrenador { get; set; }
        public DbSet<TatoRealizacion> TatoRealizacion { get; set; }
        public DbSet<TatoSeleccionado> TatoSeleccionado { get; set; }
        public DbSet<TatoSeriesEjemplo> TatoSeriesEjemplo { get; set; }
        public DbSet<tb_Suscritos> tb_Suscritos { get; set; }
        public DbSet<Team> Team { get; set; }
        public DbSet<TeamMasters> TeamMasters { get; set; }
        public DbSet<TipoAfiliado> TipoAfiliado { get; set; }
        public DbSet<TipoTorneo> TipoTorneo { get; set; }
        public DbSet<Torneo> Torneo { get; set; }
        public DbSet<TorneoDestacado> TorneoDestacado { get; set; }
        public DbSet<TorneoDestacadoMasters> TorneoDestacadoMasters { get; set; }
        public DbSet<Traspasos> Traspasos { get; set; }
        public DbSet<TraspasosEnEspera> TraspasosEnEspera { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Vivo> Vivo { get; set; }
        public DbSet<Vouchers> Vouchers { get; set; }
    }
}
