//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Noticias()
        {
            this.Comentarios = new HashSet<Comentarios>();
            this.Fotos = new HashSet<Fotos>();
        }
    
        public int NoticiaId { get; set; }
        public string Titulo { get; set; }
        public string Corta { get; set; }
        public string Larga { get; set; }
        public System.DateTime Fecha { get; set; }
        public int DisciplinaId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int CategoriaId { get; set; }
        public string Palabrasclaves { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string Youtube { get; set; }
    
        public virtual CategoriaNoticia CategoriaNoticia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        public virtual Disciplina Disciplina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotos> Fotos { get; set; }
    }
}
