//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtroEventos
    {
        public OtroEventos()
        {
            this.OtroEntradas = new HashSet<OtroEntradas>();
            this.OtroGrupal = new HashSet<OtroGrupal>();
        }
    
        public int EventoId { get; set; }
        public string EventSex { get; set; }
        public string EventNombre { get; set; }
        public int EventSerie { get; set; }
        public int TorneoId { get; set; }
        public int EdadMaxima { get; set; }
        public int EdadMinima { get; set; }
        public bool Grupal { get; set; }
        public int CantidadParticipanes { get; set; }
        public int NumeroSaltos { get; set; }
    
        public virtual ICollection<OtroEntradas> OtroEntradas { get; set; }
        public virtual OtroTorneo OtroTorneo { get; set; }
        public virtual ICollection<OtroGrupal> OtroGrupal { get; set; }
    }
}
