//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtroEntradas
    {
        public int EntradaId { get; set; }
        public int EventoId { get; set; }
        public int AtletaId { get; set; }
        public int Gorro { get; set; }
        public bool Suplente { get; set; }
        public int TorneoId { get; set; }
    
        public virtual OtroAtleta OtroAtleta { get; set; }
        public virtual OtroEventos OtroEventos { get; set; }
        public virtual OtroTorneo OtroTorneo { get; set; }
    }
}
