//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoloPosicion
    {
        public int PosicionId { get; set; }
        public int PJ { get; set; }
        public int PG { get; set; }
        public int PE { get; set; }
        public int PP { get; set; }
        public int GF { get; set; }
        public int GC { get; set; }
        public int DG { get; set; }
        public int PUNTOS { get; set; }
        public int EquipoId { get; set; }
        public int GrupoId { get; set; }
        public Nullable<int> TorneoId { get; set; }
    
        public virtual PoloEquipos PoloEquipos { get; set; }
        public virtual PoloGrupos PoloGrupos { get; set; }
        public virtual PoloTorneo PoloTorneo { get; set; }
    }
}
