//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoloGrupos
    {
        public PoloGrupos()
        {
            this.PoloPartidos = new HashSet<PoloPartidos>();
            this.PoloPosicion = new HashSet<PoloPosicion>();
        }
    
        public int GrupoId { get; set; }
        public string Nombre { get; set; }
        public int Sexoid { get; set; }
        public Nullable<int> TorneoId { get; set; }
    
        public virtual ICollection<PoloPartidos> PoloPartidos { get; set; }
        public virtual ICollection<PoloPosicion> PoloPosicion { get; set; }
    }
}
