//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoloEquipos
    {
        public PoloEquipos()
        {
            this.PoloJugadores = new HashSet<PoloJugadores>();
            this.PoloPosicion = new HashSet<PoloPosicion>();
            this.PoloPosicionFinal = new HashSet<PoloPosicionFinal>();
        }
    
        public int EquipoId { get; set; }
        public string Nombre { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> TorneoId { get; set; }
    
        public virtual ICollection<PoloJugadores> PoloJugadores { get; set; }
        public virtual ICollection<PoloPosicion> PoloPosicion { get; set; }
        public virtual ICollection<PoloPosicionFinal> PoloPosicionFinal { get; set; }
    }
}
