//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoloSetupTorneo
    {
        public int SetupId { get; set; }
        public int TorneoId { get; set; }
        public bool PermiteNoAfiliados { get; set; }
        public bool PermiteSubirEdad { get; set; }
        public bool PermiteMixtos { get; set; }
        public bool PorLigas { get; set; }
    
        public virtual PoloTorneo PoloTorneo { get; set; }
    }
}
