//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoloTorneo
    {
        public PoloTorneo()
        {
            this.PoloFechas = new HashSet<PoloFechas>();
            this.PoloGoleadores = new HashSet<PoloGoleadores>();
            this.PoloJugadores = new HashSet<PoloJugadores>();
            this.PoloPartidos = new HashSet<PoloPartidos>();
            this.PoloPosicion = new HashSet<PoloPosicion>();
            this.PoloPosicionFinal = new HashSet<PoloPosicionFinal>();
            this.PoloResultados = new HashSet<PoloResultados>();
            this.PoloRondas = new HashSet<PoloRondas>();
            this.PoloSetupTorneo = new HashSet<PoloSetupTorneo>();
        }
    
        public int TorneoId { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaCierre { get; set; }
        public int EdadMaxima { get; set; }
        public int EdadMinima { get; set; }
    
        public virtual ICollection<PoloFechas> PoloFechas { get; set; }
        public virtual ICollection<PoloGoleadores> PoloGoleadores { get; set; }
        public virtual ICollection<PoloJugadores> PoloJugadores { get; set; }
        public virtual ICollection<PoloPartidos> PoloPartidos { get; set; }
        public virtual ICollection<PoloPosicion> PoloPosicion { get; set; }
        public virtual ICollection<PoloPosicionFinal> PoloPosicionFinal { get; set; }
        public virtual ICollection<PoloResultados> PoloResultados { get; set; }
        public virtual ICollection<PoloRondas> PoloRondas { get; set; }
        public virtual ICollection<PoloSetupTorneo> PoloSetupTorneo { get; set; }
    }
}
