//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPersona
    {
        public PPersona()
        {
            this.PAlumno = new HashSet<PAlumno>();
        }
    
        public int PersonaId { get; set; }
        public string Nombre { get; set; }
        public string APaterno { get; set; }
        public string Amaterno { get; set; }
        public System.DateTime Nacimiento { get; set; }
        public string DNI { get; set; }
        public string Celular { get; set; }
        public string Nacionalidad { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<PAlumno> PAlumno { get; set; }
        public virtual PProfesor PProfesor { get; set; }
    }
}
