//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public Nullable<int> tag_ptr { get; set; }
        public string tag_gender { get; set; }
        public string tag_indrel { get; set; }
        public Nullable<int> tag_dist { get; set; }
        public string tag_stroke { get; set; }
        public Nullable<short> low_age { get; set; }
        public Nullable<short> high_Age { get; set; }
        public Nullable<short> Record_month { get; set; }
        public Nullable<short> Record_day { get; set; }
        public Nullable<short> Record_year { get; set; }
        public string Record_Holder { get; set; }
        public string Record_Holderteam { get; set; }
        public string Relay_Names { get; set; }
        public Nullable<float> Record_Time { get; set; }
        public string Record_course { get; set; }
        public string div_abbr { get; set; }
        public string Record_teamabbr { get; set; }
        public string Record_teamlsc { get; set; }
        public int RecordId { get; set; }
    }
}
