//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordsActuales
    {
        public int RecordId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Torneo { get; set; }
        public int PruebaId { get; set; }
        public int EdadId { get; set; }
        public double TiempoSegundos { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Nombre3 { get; set; }
        public string Nombre4 { get; set; }
        public Nullable<double> split1 { get; set; }
        public Nullable<double> split2 { get; set; }
        public Nullable<double> split3 { get; set; }
        public string Equipo { get; set; }
        public int TipoId { get; set; }
        public string PiscinaId { get; set; }
        public Nullable<double> split4 { get; set; }
    
        public virtual Piscinas Piscinas { get; set; }
        public virtual RecordsEdades RecordsEdades { get; set; }
        public virtual RecordsPruebas RecordsPruebas { get; set; }
        public virtual RecordTipo RecordTipo { get; set; }
    }
}
