//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saltos
    {
        public Nullable<double> Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> A { get; set; }
        public Nullable<double> B { get; set; }
        public Nullable<double> C { get; set; }
        public Nullable<double> D { get; set; }
        public Nullable<double> Altura { get; set; }
        public string Tipo { get; set; }
        public int SaltoId { get; set; }
    }
}
