//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetupTorneo
    {
        public int SetupId { get; set; }
        public int TipoId { get; set; }
        public int pruebasXsesion { get; set; }
        public int pruebasXtorneo { get; set; }
        public int Meetid { get; set; }
        public bool PorLigas { get; set; }
        public int pruebasXEquipo { get; set; }
        public int SinMarca { get; set; }
    
        public virtual TipoTorneo TipoTorneo { get; set; }
        public virtual Torneo Torneo { get; set; }
    }
}
