//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagNames
    {
        public int tag_ptr { get; set; }
        public string tag_name { get; set; }
        public bool for_scoring { get; set; }
        public bool for_entryqual { get; set; }
        public bool for_timestd { get; set; }
        public string tag_desc { get; set; }
        public int TagId { get; set; }
        public int MeetId { get; set; }
    }
}
