//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TatoSeriesEjemplo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TatoSeriesEjemplo()
        {
            this.TatoInformeEntrenador = new HashSet<TatoInformeEntrenador>();
        }
    
        public int SerieId { get; set; }
        public int Zona { get; set; }
        public int Series { get; set; }
        public int Repeticiones { get; set; }
        public int Parcial { get; set; }
        public double Tolerancia { get; set; }
        public double Micropausa { get; set; }
        public int Piscina { get; set; }
        public string Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TatoInformeEntrenador> TatoInformeEntrenador { get; set; }
    }
}
