//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmarca
    {
        public Nullable<double> Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Notengoidea { get; set; }
        public string Iniciales { get; set; }
        public Nullable<int> familia1 { get; set; }
        public Nullable<int> familia2 { get; set; }
        public Nullable<int> familia3 { get; set; }
        public Nullable<int> familia4 { get; set; }
        public Nullable<int> familia5 { get; set; }
        public Nullable<int> familia6 { get; set; }
        public Nullable<int> Familia { get; set; }
        public int F12 { get; set; }
    }
}
