//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraspasosEnEspera
    {
        public int eEsperaId { get; set; }
        public string DNI { get; set; }
        public int ClubSolicitante { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Liberado { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
        public virtual Club Club { get; set; }
    }
}
