//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traspasos
    {
        public int TraspasoId { get; set; }
        public int UsuarioId { get; set; }
        public int ClubId { get; set; }
        public string Numero_de_operacion { get; set; }
        public System.DateTime Fecha_de_traspaso { get; set; }
        public int Numero_de_traspasos { get; set; }
        public double Monto { get; set; }
        public int Traspasos_restantes { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
