//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FDPN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vouchers
    {
        public Vouchers()
        {
            this.Afiliacion = new HashSet<Afiliacion>();
        }
    
        public int VoucherId { get; set; }
        public double Monto { get; set; }
        public int Numero_de_afiliados { get; set; }
        public int Numero_de_reafiliados { get; set; }
        public int UsuarioId { get; set; }
        public int AfiliadosRestantes { get; set; }
        public int ReafiliadosRestantes { get; set; }
        public int ClubId { get; set; }
        public System.DateTime Fecha_de_creacion { get; set; }
        public System.DateTime Fecha_de_modificacion { get; set; }
        public string Nro__operacion { get; set; }
        public Nullable<int> Numero_de_vinculados { get; set; }
        public Nullable<int> VinculadosRestantes { get; set; }
    
        public virtual ICollection<Afiliacion> Afiliacion { get; set; }
        public virtual Club Club { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
